global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django-containers'
    metrics_path: /metrics

    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"

    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: web
        action: keep

      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        replacement: '$1:5000'
        target_label: __address__

      - source_labels: [__meta_docker_container_name]
        target_label: instance