@startuml

node "Poste Utilisateur" as client {
    artifact "navigateur web"
}

node "Serveur Django (POS)" as app {
    artifact "views.py"
    artifact "urls.py"
    artifact "apps.py"
    artifact "admin.py"
    artifact "models.py"
    artifact "services/MagasinService.py"
    artifact "services/ProduitService.py"
    artifact "services/VenteService.py"
    artifact "services/StockService.py"
    artifact "asgi.py"
    artifact "wsgi.py"
    artifact "settings.py"
    artifact "management/commands/initialise_db.py"
}

node "Serveur Tests" as test {
    artifact "tests.py"
}

database "Base de données\nMySQL" as db

client --> app : Requêtes HTTP (interface web)
app --> db : ORM Django (SQL)
test --> app : Appels Django TestCase

@enduml