@startuml

node "Poste Utilisateur" as client {
    artifact "navigateur web"
}

node "NGINX" as nginx {
    artifact "nginx.conf"
}

node "Serveur Django (POS)" as app {
    artifact "views.py"
    artifact "urls.py"
    artifact "apps.py"
    artifact "admin.py"
    artifact "models.py"
    artifact "services/MagasinService.py"
    artifact "services/ProduitService.py"
    artifact "services/VenteService.py"
    artifact "services/StockService.py"
    artifact "services/PanierService.py"
    artifact "asgi.py"
    artifact "wsgi.py"
    artifact "settings.py"
    artifact "management/commands/initialise_db.py"
}

node "Serveur Tests" as test {
    artifact "tests.py"
}

database "Base de données\nMySQL" as db

node "Prometheus" as prometheus {
    artifact "Prometheus/prometheus.yml"
}

node "Grafana" as grafana

node "Redis" as redis

node "k6" as k6 {
    artifact "k6_files/load_test.js"
    artifact "k6_files/test_consultation_stocks.js"
}

client --> nginx : Requêtes HTTP (interface web)
nginx --> app : Proxy pass (trafic HTTP, /metrics)
app --> db : ORM Django (SQL)
app --> redis : Cache/session
test --> app : Appels Django TestCase
prometheus --> app : Scrape /metrics
grafana --> prometheus : Requêtes métriques
k6 --> nginx : Tests de charge (HTTP)

@enduml