@startuml

start

:Utilisateur accède à l'application via le navigateur web;
:Requête HTTP envoyée à views.py;

partition "views.py" {
    :Analyse de l'URL (urls.py);
    :Appel de la vue appropriée;
    if (Page caisse ?) then (oui)
        :page_caisse();
        :Appel StockService.get_stock_par_magasin();
        :Rendu du template caisse.html;
    else if (Recherche produit ?) then (oui)
        :rechercher_produit();
        :Appel ProduitService.rechercher_produits_par_nom_ou_id();
        :Rendu du template caisse.html;
    else if (Ajouter au panier ?) then (oui)
        :ajouter_au_panier();
        :Appel StockService.get_stock_entry();
        :Mise à jour session panier;
        :Redirection vers panier.html;
    else if (Finaliser vente ?) then (oui)
        :finaliser_vente();
        :Appel VenteService.creer_vente();
        :Mise à jour Stock et création Vente/VenteProduit;
        :Redirection vers vente.html;
    else if (Réapprovisionnement ?) then (oui)
        :reapprovisionnement_view();
        :Appel StockService.transferer_stock();
        :Rendu reapprovisionner.html;
    else if (Administration ?) then (oui)
        :admin_page();
        :Appel MagasinService.get_all_magasins();
        :Rendu gestion.html;
    endif
}

:views.py utilise les services (ProduitService, StockService, VenteService, MagasinService);
:Les services accèdent aux modèles (models.py);
:Les modèles interagissent avec la base de données (MySQL);

stop

@enduml